### ISSUE TITLE
Zigbee Gerät kann nicht angesprochen werden

### ISSUE THREAD

**Issue by demedved** [o0shojo0o/AlexaNodeRedImporter_Script#1]
Moin,

ich habe das Skript bei mir hinzugefügt, erhalte aber bei jedem Trigger folgenden Fehler:

```
javascript.0 | 174 | 2022-02-20 01:05:25.392 | error | at processImmediate (internal/timers.js:464:21)
javascript.0 | 174 | 2022-02-20 01:05:25.392 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5708:41)
javascript.0 | 174 | 2022-02-20 01:05:25.391 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:530:29)
javascript.0 | 174 | 2022-02-20 01:05:25.391 | error | at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1082:38)
javascript.0 | 174 | 2022-02-20 01:05:25.390 | error | at Object.<anonymous> (script.js.AlexaToNodeRed.script:45:18)
javascript.0 | 174 | 2022-02-20 01:05:25.388 | error | Error in callback: TypeError: Cannot read property 'zigbee.0.0017880108d6c898' of null
```

Das genannte Gerät (zigbee.0.0017880108d6c898) ist vorhanden und ansprechbar, ansonsten habe ich auch andere Geräte ausprobiert. Habe leider gar keine Idee, wie ich hier weiterkommen soll.

Vielen Dank für die Hilfe!

**Comment by o0shojo0o** [comment]
Moin, 

stoppe mal das Script und lösche den Datenpunkt `0_userdata.0.AlexaToNodeRed.Database` und starte das Script wieder.
Es scheint das dort was schiefgelaufen ist.

**Comment by demedved** [comment]
Das war die Lösung, vielen Dank!
